function renderAdmin(){
 $('statBrands').textContent=data.brands.length;$('statItems').textContent=data.items.length;$('statStock').textContent=data.items.reduce((s,i)=>s+Number(i.stock||0),0);$('statReserved').textContent=data.items.reduce((s,i)=>s+reserved(i.id),0);
 $('itemBrand').innerHTML=data.brands.map(b=>`<option value="${b.id}">${esc(b.name)}</option>`).join('');$('addItem').disabled=!data.brands.length;
 $('brandList').innerHTML=data.brands.length?data.brands.map(b=>{const n=data.items.filter(i=>i.brandId===b.id).length;return`<div class="row"><div><div class="rtitle">${esc(b.name)}</div><div class="rsub">${n} saved item${n===1?'':'s'}</div></div><div><span class="badge ${b.active?'on':'off'}">${b.active?'Shown in Store':'Hidden'}</span></div><div class="row-actions"><button class="btn small" data-tb="${b.id}">${b.active?'Hide':'Show'}</button><button class="btn small ghost" data-eb="${b.id}">Edit</button><button class="btn small danger" data-db="${b.id}">Delete</button></div></div>`}).join(''):'<div class="empty">No vendors yet.</div>';
 $('brandList').querySelectorAll('[data-tb]').forEach(x=>x.onclick=()=>{const b=brand(x.dataset.tb);b.active=!b.active;save()});$('brandList').querySelectorAll('[data-eb]').forEach(x=>x.onclick=()=>editBrand(x.dataset.eb));$('brandList').querySelectorAll('[data-db]').forEach(x=>x.onclick=()=>openDeleteVendor(x.dataset.db));
 const items=[...data.items].sort((a,b)=>(brand(a.brandId)?.name||'').localeCompare(brand(b.brandId)?.name||'')||a.name.localeCompare(b.name));
 $('itemList').innerHTML=items.length?items.map(i=>{const av=available(i),res=reserved(i.id);return`<div class="row"><div><div class="rtitle">${esc(i.name)} <span style="color:var(--muted);font-weight:750">${money(i.price)}</span></div><div class="rsub">${esc(brand(i.brandId)?.name||'No vendor')} · <span class="badge ${i.active?'on':'off'}">${i.active?'Customer Item':'Hidden'}</span> ${av<=i.lowStock?`<span class="badge low">Low at ${i.lowStock}</span>`:''}</div></div><div><div class="stock-box"><button class="btn tiny" data-stock="${i.id}" data-d="-10">−10</button><button class="btn tiny" data-stock="${i.id}" data-d="-5">−5</button><button class="btn tiny" data-stock="${i.id}" data-d="-1">−1</button><span class="stock-num">${i.stock}</span><button class="btn tiny" data-stock="${i.id}" data-d="1">+1</button><button class="btn tiny" data-stock="${i.id}" data-d="5">+5</button><button class="btn tiny" data-stock="${i.id}" data-d="10">+10</button></div><div class="rsub">Available: ${av}${res?` · Reserved: ${res}`:''}</div></div><div class="row-actions"><button class="btn small" data-ti="${i.id}">${i.active?'Hide':'Show'}</button><button class="btn small ghost" data-ei="${i.id}">Edit / Exact Qty</button><button class="btn small danger" data-di="${i.id}">Delete</button></div></div>`}).join(''):'<div class="empty">Your item library is empty. Add your first item above.</div>';
 $('itemList').querySelectorAll('[data-stock]').forEach(x=>x.onclick=()=>adjustStock(x.dataset.stock,Number(x.dataset.d)));$('itemList').querySelectorAll('[data-ti]').forEach(x=>x.onclick=()=>{const i=item(x.dataset.ti);i.active=!i.active;save()});$('itemList').querySelectorAll('[data-ei]').forEach(x=>x.onclick=()=>editItem(x.dataset.ei));$('itemList').querySelectorAll('[data-di]').forEach(x=>x.onclick=()=>deleteItem(x.dataset.di));
 $('pickupItemSelect').innerHTML=data.items.map(i=>`<option value="${i.id}">${esc(brand(i.brandId)?.name||'Unknown')} — ${esc(i.name)} (${available(i)} available)</option>`).join('');$('addPickupLine').disabled=!data.items.length;
 renderPickupDraft();renderPickups();renderSales();renderInventoryHistory();renderDashboard();
}
function adjustStock(id,delta){const i=item(id);if(!i)return;const min=reserved(i.id);const next=Number(i.stock)+delta;if(next<min)return alert(`You cannot reduce ${i.name} below ${min} because ${min} are reserved for pickup orders.`);i.stock=Math.max(0,next);logStock(i,delta,'Manual adjustment');save()}
function deleteItem(id){const i=item(id);if(!i)return;if(reserved(id)>0)return alert('This item is reserved on an active pickup order. Cancel or complete that pickup before deleting the item.');if(confirm(`Permanently delete ${i.name}?\n\nUse Hide instead if you may sell it again.`)){data.items=data.items.filter(a=>a.id!==id);delete cart[id];pickupDraft=pickupDraft.filter(x=>x.itemId!==id);save()}}
function editBrand(id){const b=brand(id);edit={type:'brand',id};$('editTitle').textContent='Edit Vendor / Brand';$('editBody').innerHTML=`<div class="field" style="margin-top:15px"><label>Vendor / brand name</label><input id="editBrandName" value="${esc(b.name)}"></div>`;$('editOverlay').classList.remove('hidden')}
function editItem(id){const i=item(id);edit={type:'item',id};$('editTitle').textContent='Edit Item';$('editBody').innerHTML=`<div class="form two" style="margin-top:15px"><div class="field"><label>Vendor / Brand</label><select id="editItemBrand">${data.brands.map(b=>`<option value="${b.id}" ${b.id===i.brandId?'selected':''}>${esc(b.name)}</option>`).join('')}</select></div><div class="field"><label>Item name</label><input id="editItemName" value="${esc(i.name)}"></div><div class="field"><label>Price</label><input id="editItemPrice" type="number" min="0" step="0.01" value="${Number(i.price).toFixed(2)}"></div><div class="field"><label>Exact inventory quantity</label><input id="editItemStock" type="number" min="${reserved(i.id)}" step="1" value="${i.stock}"></div><div class="field"><label>Low-stock warning at</label><input id="editItemLow" type="number" min="0" step="1" value="${i.lowStock}"></div></div><p class="hint">${reserved(i.id)} currently reserved for pickup orders.</p>`;$('editOverlay').classList.remove('hidden')}
function saveEdit(){if(!edit)return;if(edit.type==='brand'){const b=brand(edit.id),name=$('editBrandName').value.trim();if(!name)return alert('Enter a vendor name.');b.name=name}else{const i=item(edit.id),name=$('editItemName').value.trim(),price=Number($('editItemPrice').value),stock=Math.floor(Number($('editItemStock').value)),low=Math.floor(Number($('editItemLow').value||0)),oldStock=i.stock;if(!name||!Number.isFinite(price)||price<0||!Number.isFinite(stock)||stock<reserved(i.id)||!Number.isFinite(low)||low<0)return alert('Check the item name, price, inventory, and low-stock amount.');i.brandId=$('editItemBrand').value;i.name=name;i.price=price;i.stock=stock;i.lowStock=low;if(stock!==oldStock)logStock(i,stock-oldStock,'Exact quantity adjustment')}$('editOverlay').classList.add('hidden');edit=null;save()}
function openDeleteVendor(id){const b=brand(id),items=data.items.filter(i=>i.brandId===id);vendorDeleteId=id;if(!items.length){$('vendorDeleteBody').innerHTML=`<p>Delete <strong>${esc(b.name)}</strong>?</p><p class="hint">Past sales will keep the vendor name in history.</p>`;$('vendorDeleteConfirm').textContent='Delete Vendor';$('vendorDeleteConfirm').dataset.mode='empty'}else{const others=data.brands.filter(x=>x.id!==id);$('vendorDeleteBody').innerHTML=`<p><strong>${esc(b.name)}</strong> has ${items.length} saved product${items.length===1?'':'s'}.</p><div class="field"><label>What should happen to those products?</label><select id="vendorDeleteMode"><option value="move" ${others.length?'':'disabled'}>Move products to another vendor</option><option value="all">Delete vendor and all products</option></select></div><div class="field" id="moveVendorWrap" style="margin-top:10px"><label>Move products to</label><select id="moveVendorTarget">${others.map(x=>`<option value="${x.id}">${esc(x.name)}</option>`).join('')}</select></div><div class="notice"><strong>Past sales will not be deleted.</strong> Historical receipts and vendor totals keep the original vendor name.</div>`;$('vendorDeleteConfirm').textContent='Continue';$('vendorDeleteConfirm').dataset.mode='products';const mode=$('vendorDeleteMode');const toggle=()=>{$('moveVendorWrap').classList.toggle('hidden',mode.value!=='move')};mode.onchange=toggle;toggle()}$('vendorDeleteOverlay').classList.remove('hidden')}
function confirmDeleteVendor(){const b=brand(vendorDeleteId);if(!b)return;if($('vendorDeleteConfirm').dataset.mode==='empty'){data.brands=data.brands.filter(x=>x.id!==b.id)}else{const mode=$('vendorDeleteMode').value;if(mode==='move'){const target=$('moveVendorTarget')?.value;if(!target)return alert('Choose another vendor.');data.items.filter(i=>i.brandId===b.id).forEach(i=>i.brandId=target)}else{const ids=new Set(data.items.filter(i=>i.brandId===b.id).map(i=>i.id));const blocked=[...ids].some(id=>reserved(id)>0);if(blocked)return alert('One or more products are reserved on active pickup orders. Cancel or complete those pickup orders first.');if(!confirm(`Delete ${b.name} and all of its saved products? This cannot be undone.`))return;data.items=data.items.filter(i=>!ids.has(i.id));Object.keys(cart).forEach(id=>{if(ids.has(id))delete cart[id]});pickupDraft=pickupDraft.filter(x=>!ids.has(x.itemId))}data.brands=data.brands.filter(x=>x.id!==b.id)}vendorDeleteId=null;$('vendorDeleteOverlay').classList.add('hidden');save()}
