const V2='riseRoostRegisterDataV2',V1='riseRoostRegisterDataV1',PIN='riseRoostRegisterPinV1';
const $=id=>document.getElementById(id),uid=p=>p+'_'+Date.now().toString(36)+Math.random().toString(36).slice(2,7),money=n=>'$'+Number(n||0).toFixed(2),esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function migrate(d){d=d&&typeof d==='object'?d:{};d.brands=Array.isArray(d.brands)?d.brands:[];d.items=Array.isArray(d.items)?d.items:[];d.sales=Array.isArray(d.sales)?d.sales:[];d.pickups=Array.isArray(d.pickups)?d.pickups:[];d.stockLog=Array.isArray(d.stockLog)?d.stockLog:[];d.items.forEach(i=>{i.stock=Math.max(0,Number(i.stock||0));i.lowStock=Number.isFinite(Number(i.lowStock))?Math.max(0,Math.floor(Number(i.lowStock))):2;i.active=i.active!==false});d.brands.forEach(b=>b.active=b.active!==false);return d}
function load(){try{const d=JSON.parse(localStorage.getItem(V2));if(d)return migrate(d)}catch(e){}try{const old=JSON.parse(localStorage.getItem(V1));if(old){const d=migrate(old);localStorage.setItem(V2,JSON.stringify(d));return d}}catch(e){}const d=migrate({brands:[{id:uid('brand'),name:'Rise & Roost',active:true}],items:[],sales:[],pickups:[],stockLog:[]});localStorage.setItem(V2,JSON.stringify(d));return d}
let data=load(),cart={},pickupDraft=[],edit=null,pinMode='login',firstPin='',vendorDeleteId=null;
function persist(){localStorage.setItem(V2,JSON.stringify(data))}
function save(){persist();renderAll()}
function brand(id){return data.brands.find(b=>b.id===id)}function item(id){return data.items.find(i=>i.id===id)}
function activeReservations(itemId,excludePickupId=null){return data.pickups.filter(p=>p.id!==excludePickupId&&['ready','waiting'].includes(p.status)).reduce((s,p)=>s+p.items.filter(x=>x.itemId===itemId).reduce((a,x)=>a+Number(x.qty||0),0),0)}
function reserved(itemId){return activeReservations(itemId)}function available(i){return Math.max(0,Number(i.stock||0)-reserved(i.id))}
function logStock(i,delta,reason){data.stockLog.unshift({id:uid('log'),date:new Date().toISOString(),itemId:i.id,itemName:i.name,brandId:i.brandId,brandName:brand(i.brandId)?.name||'Unknown',delta:Number(delta),stockAfter:Number(i.stock),reason:reason||'Adjustment'});if(data.stockLog.length>1000)data.stockLog.length=1000}
function entries(){return Object.entries(cart).map(([id,qty])=>({item:item(id),qty:Number(qty)})).filter(x=>x.item&&x.qty>0)}function total(){return entries().reduce((s,x)=>s+Number(x.item.price)*x.qty,0)}
function renderStore(){const visibleBrands=data.brands.filter(b=>b.active);let html='';visibleBrands.forEach(b=>{const items=data.items.filter(i=>i.brandId===b.id&&i.active);if(!items.length)return;html+=`<section class="vendor"><div class="vendor-head"><h3>${esc(b.name)}</h3><span>${items.length} item${items.length===1?'':'s'}</span></div><div class="grid">`;items.forEach(i=>{const av=available(i),low=av>0&&av<=i.lowStock;html+=`<button class="product ${av===0?'sold':''} ${low?'low':''}" data-buy="${i.id}" ${av===0?'disabled':''}><div class="pname">${esc(i.name)}</div><div class="pfoot"><div class="price">${money(i.price)}</div><div class="stock">${av===0?'SOLD OUT':`${av} available${low?' · LOW':''}`}</div></div></button>`});html+='</div></section>'});$('productArea').innerHTML=html||'<div class="empty">No items are available right now.</div>';$('productArea').querySelectorAll('[data-buy]').forEach(btn=>btn.onclick=()=>addToCart(btn.dataset.buy))}
function addToCart(id){const i=item(id),av=available(i);if(!i||av<=0)return;const current=Number(cart[id]||0);if(current>=av)return alert('That is all that is currently available.');cart[id]=current+1;renderCart()}
function changeQty(id,d){const i=item(id);if(!i)return;const next=Number(cart[id]||0)+d;if(next<=0)delete cart[id];else if(next<=available(i))cart[id]=next;else alert('That is all that is currently available.');renderCart()}
function renderCart(){const e=entries();$('cartHint').textContent=e.length?'Review your items before paying.':'Nothing added yet.';$('cartList').innerHTML=e.map(x=>`<div class="cart-row"><div><div class="cname">${esc(x.item.name)}</div><div class="cbrand">${esc(brand(x.item.brandId)?.name||'Unknown')}</div><button class="remove" data-remove="${x.item.id}">Remove</button></div><div><div class="cline">${money(Number(x.item.price)*x.qty)}</div><div class="qtys"><button class="qbtn" data-q="${x.item.id}" data-d="-1">−</button><span class="qnum">${x.qty}</span><button class="qbtn" data-q="${x.item.id}" data-d="1">+</button></div></div></div>`).join('');$('cartList').querySelectorAll('[data-q]').forEach(x=>x.onclick=()=>changeQty(x.dataset.q,Number(x.dataset.d)));$('cartList').querySelectorAll('[data-remove]').forEach(x=>x.onclick=()=>{delete cart[x.dataset.remove];renderCart()});$('cartTotal').textContent=money(total());$('payBtn').disabled=!e.length;$('clearBtn').disabled=!e.length}
function checkout(){for(const x of entries())if(x.qty>available(x.item))return alert(`${x.item.name} no longer has enough available inventory. Please adjust the order.`);$('payTotal').textContent=money(total());$('payOverlay').classList.remove('hidden')}
function recordSale(lines,opts={}){const sale={id:uid('sale'),date:new Date().toISOString(),total:lines.reduce((s,x)=>s+Number(x.price)*Number(x.qty),0),items:lines.map(x=>({...x})),payment:opts.payment||'cash',source:opts.source||'store',pickupId:opts.pickupId||null,voided:false};data.sales.unshift(sale);return sale}
function finish(){const e=entries();if(!e.length)return;for(const x of e)if(x.qty>available(x.item))return alert(`${x.item.name} no longer has enough available inventory.`);const lines=e.map(x=>({itemId:x.item.id,itemName:x.item.name,brandId:x.item.brandId,brandName:brand(x.item.brandId)?.name||'Unknown',price:Number(x.item.price),qty:x.qty}));e.forEach(x=>{x.item.stock=Math.max(0,x.item.stock-x.qty);logStock(x.item,-x.qty,'Customer sale')});recordSale(lines,{payment:'cash',source:'store'});cart={};persist();$('payOverlay').classList.add('hidden');$('thanks').classList.remove('hidden');renderAll()}
function todaySales(){const today=new Date().toDateString();return data.sales.filter(s=>!s.voided&&new Date(s.date).toDateString()===today)}
function renderDashboard(){const sales=todaySales();$('dashSalesToday').textContent=money(sales.reduce((s,x)=>s+Number(x.total),0));$('dashItemsToday').textContent=sales.reduce((s,x)=>s+x.items.reduce((a,i)=>a+Number(i.qty),0),0);$('dashCashToday').textContent=money(sales.filter(s=>s.payment==='cash').reduce((a,s)=>a+Number(s.total),0));const lows=data.items.filter(i=>i.active&&brand(i.brandId)?.active&&available(i)<=Number(i.lowStock||0));$('dashLowStock').textContent=lows.length;$('lowStockList').innerHTML=lows.length?lows.map(i=>`<div class="row"><div><div class="rtitle">${esc(i.name)}</div><div class="rsub">${esc(brand(i.brandId)?.name||'Unknown')}</div></div><div><span class="badge ${available(i)===0?'off':'low'}">${available(i)===0?'Sold Out':`${available(i)} available`}</span></div><div class="row-actions"><button class="btn small" data-gotoitem="${i.id}">Adjust</button></div></div>`).join(''):'<div class="empty">No low-stock items.</div>';$('lowStockList').querySelectorAll('[data-gotoitem]').forEach(b=>b.onclick=()=>{showTab('items');editItem(b.dataset.gotoitem)});const ready=data.pickups.filter(p=>p.status==='ready');$('readyPickupList').innerHTML=ready.length?ready.slice(0,10).map(p=>`<div class="row"><div><div class="rtitle">${esc(p.customerName)}</div><div class="rsub">Code ${esc(p.code)} · ${p.items.reduce((s,i)=>s+i.qty,0)} item(s)</div></div><div><span class="status ready">Ready</span></div><div class="row-actions"><button class="btn small" data-openpickup="${p.id}">Open</button></div></div>`).join(''):'<div class="empty">No pickup orders are ready.</div>';$('readyPickupList').querySelectorAll('[data-openpickup]').forEach(b=>b.onclick=()=>{showTab('pickups');setTimeout(()=>document.querySelector(`[data-pickup="${b.dataset.openpickup}"]`)?.scrollIntoView({behavior:'smooth',block:'center'}),50)})}
