function showPin(mode='login'){pinMode=mode;firstPin='';$('pinInput').value='';const has=!!localStorage.getItem(PIN);if(mode==='login'&&!has){pinMode='create1';$('pinTitle').textContent='Create Admin PIN';$('pinHelp').textContent='Choose a 4–6 digit PIN. Customers will need it to enter the admin area.'}else if(mode==='login'){$('pinTitle').textContent='Admin PIN';$('pinHelp').textContent='Enter the admin PIN.'}else{pinMode='create1';$('pinTitle').textContent='New Admin PIN';$('pinHelp').textContent='Choose a new 4–6 digit PIN.'}$('pinOverlay').classList.remove('hidden');setTimeout(()=>$('pinInput').focus(),100)}
function pinSubmit(){const v=$('pinInput').value.trim();if(!/^\d{4,6}$/.test(v))return alert('Use a 4–6 digit number.');if(pinMode==='login'){if(v!==localStorage.getItem(PIN))return alert('Incorrect PIN.');$('pinOverlay').classList.add('hidden');$('adminScreen').classList.remove('hidden');renderAdmin();return}if(pinMode==='create1'){firstPin=v;pinMode='create2';$('pinTitle').textContent='Confirm Admin PIN';$('pinHelp').textContent='Enter the same PIN again.';$('pinInput').value='';return $('pinInput').focus()}if(v!==firstPin){pinMode='create1';firstPin='';$('pinTitle').textContent='Create Admin PIN';$('pinHelp').textContent='The PINs did not match. Try again.';$('pinInput').value='';return}localStorage.setItem(PIN,v);$('pinOverlay').classList.add('hidden');$('adminScreen').classList.remove('hidden');renderAdmin()}
function showTab(name){document.querySelectorAll('.tab').forEach(t=>t.classList.toggle('active',t.dataset.tab===name));['dashboard','items','pickups','sales','inventory','settings'].forEach(n=>$(n+'Tab').classList.toggle('hidden',n!==name));if(name==='dashboard')renderDashboard();if(name==='sales')renderSales();if(name==='pickups')renderPickups();if(name==='inventory')renderInventoryHistory()}
function showStoreTab(name){document.querySelectorAll('.store-tab').forEach(t=>t.classList.toggle('active',t.dataset.storetab===name));$('shopView').classList.toggle('hidden',name!=='shop');$('pickupView').classList.toggle('hidden',name!=='pickup');if(name==='pickup'){$('pickupCodeInput').value='';$('pickupCustomerResult').innerHTML=''}}
function exportBackup(){const blob=new Blob([JSON.stringify({version:2,exportedAt:new Date().toISOString(),data},null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`rise-and-roost-backup-${new Date().toISOString().slice(0,10)}.json`;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000)}
function importBackup(){const f=$('importBackupFile').files[0];if(!f)return alert('Choose a backup file first.');const r=new FileReader();r.onload=()=>{try{const parsed=JSON.parse(r.result),incoming=migrate(parsed.data||parsed);if(!confirm('Import this backup?\n\nThis will replace the register data currently saved on this device.'))return;data=incoming;persist();cart={};pickupDraft=[];renderAll();alert('Backup imported successfully.')}catch(e){alert('That file does not appear to be a valid Rise & Roost backup.')}};r.readAsText(f)}
function renderAll(){renderStore();renderCart();renderAdmin()}
$('payBtn').onclick=checkout;$('clearBtn').onclick=()=>{if(confirm('Clear this order?')){cart={};renderCart()}};$('backPay').onclick=()=>$('payOverlay').classList.add('hidden');$('finishSale').onclick=finish;$('doneThanks').onclick=()=>$('thanks').classList.add('hidden');$('adminBtn').onclick=()=>showPin('login');$('pinCancel').onclick=()=>$('pinOverlay').classList.add('hidden');$('pinGo').onclick=pinSubmit;$('pinInput').onkeydown=e=>{if(e.key==='Enter')pinSubmit()};$('exitAdmin').onclick=()=>$('adminScreen').classList.add('hidden');
$('addBrand').onclick=()=>{const name=$('brandName').value.trim();if(!name)return alert('Enter a vendor name.');if(data.brands.some(b=>b.name.toLowerCase()===name.toLowerCase()))return alert('That vendor is already saved.');data.brands.push({id:uid('brand'),name,active:true});$('brandName').value='';save()};
$('addItem').onclick=()=>{const brandId=$('itemBrand').value,name=$('itemName').value.trim(),price=Number($('itemPrice').value),stock=Math.floor(Number($('itemStock').value||0)),low=Math.floor(Number($('itemLow').value||0));if(!brandId)return alert('Add a vendor first.');if(!name)return alert('Enter an item name.');if(!Number.isFinite(price)||price<0)return alert('Enter a valid price.');if(!Number.isFinite(stock)||stock<0)return alert('Enter a valid inventory amount.');if(!Number.isFinite(low)||low<0)return alert('Enter a valid low-stock amount.');const i={id:uid('item'),brandId,name,price,stock,lowStock:low,active:true};data.items.push(i);if(stock)logStock(i,stock,'Starting inventory');$('itemName').value='';$('itemPrice').value='';$('itemStock').value='';save()};
$('editCancel').onclick=()=>{$('editOverlay').classList.add('hidden');edit=null};$('editSave').onclick=saveEdit;$('changePin').onclick=()=>showPin('change');$('vendorDeleteCancel').onclick=()=>{$('vendorDeleteOverlay').classList.add('hidden');vendorDeleteId=null};$('vendorDeleteConfirm').onclick=confirmDeleteVendor;
$('addPickupLine').onclick=addPickupLine;$('createPickupBtn').onclick=createPickup;$('findPickupBtn').onclick=findPickup;$('pickupCodeInput').onkeydown=e=>{if(e.key==='Enter')findPickup()};$('exportBackup').onclick=exportBackup;$('importBackup').onclick=importBackup;
document.querySelectorAll('.tab').forEach(t=>t.onclick=()=>showTab(t.dataset.tab));document.querySelectorAll('.store-tab').forEach(t=>t.onclick=()=>showStoreTab(t.dataset.storetab));
renderAll();
