(()=>{
const s=document.createElement('style');s.textContent=`
.kiosk-home{width:min(900px,calc(100% - 24px));margin:24px auto 40px;text-align:center}.kiosk-home h1{font-size:clamp(2rem,6vw,3.5rem);margin:8px 0}.kiosk-home .lead{font-size:1.1rem;color:var(--muted);margin:0 0 22px}.kiosk-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:14px}.kiosk-choice{min-height:170px;border:1px solid var(--line);border-radius:22px;background:#fff;padding:22px 16px;box-shadow:var(--shadow);font-weight:950;font-size:1.35rem;color:var(--ink)}.kiosk-choice span,.roost-action span{display:block;margin-top:8px;font-size:.9rem;font-weight:700;color:var(--muted)}.kiosk-choice:active,.roost-action:active{transform:scale(.985)}.layout>.back-home{grid-column:1/-1;justify-self:start;margin-bottom:-2px}.roost-hub,.join-wrap{width:min(760px,calc(100% - 24px));margin:18px auto 40px}.roost-actions{display:grid;grid-template-columns:1fr 1fr;gap:14px;margin-top:16px}.roost-action{min-height:150px;border:1px solid var(--line);border-radius:20px;background:#fff;padding:20px;font-weight:950;font-size:1.25rem}.join-form{display:grid;gap:12px;margin-top:16px}.join-form .field input{min-height:54px;font-size:1.05rem}.consent{display:flex;gap:10px;align-items:flex-start;padding:8px 0}.consent input{width:22px;height:22px;margin-top:1px}.welcome-roost{text-align:center}.credit-number{font-size:3.4rem;font-weight:950;margin:8px 0}.member-contact{font-size:.82rem;color:var(--muted);margin-top:4px;word-break:break-word}.store-tabs{display:none!important}@media(max-width:700px){.kiosk-grid,.roost-actions{grid-template-columns:1fr}.kiosk-choice,.roost-action{min-height:110px}}
`;document.head.appendChild(s);
const phoneKey=x=>String(x||'').replace(/\D/g,''),emailOK=x=>/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(x);
function ensure(){data.customers=Array.isArray(data.customers)?data.customers:[];data.customers.forEach(c=>{c.phone=String(c.phone||'');c.email=String(c.email||'');c.pickupAlerts=!!c.pickupAlerts;c.storeUpdates=!!c.storeUpdates})}ensure();persist();
function hideViews(){['kioskHome','shopView','pickupView','cartonView','roostHub','joinView'].forEach(id=>$(id)?.classList.add('hidden'))}
function home(){hideViews();$('kioskHome').classList.remove('hidden');window.scrollTo(0,0)}
function shop(){hideViews();$('shopView').classList.remove('hidden');renderStore();renderCart();window.scrollTo(0,0)}
function pickup(){hideViews();$('pickupView').classList.remove('hidden');$('pickupCodeInput').value='';$('pickupCustomerResult').innerHTML='';window.scrollTo(0,0)}
function roost(){hideViews();$('roostHub').classList.remove('hidden');window.scrollTo(0,0)}
function cartons(id=''){hideViews();$('cartonView').classList.remove('hidden');renderAll();if(id){$('cartonCustomerSelect').value=id;$('cartonCustomerSelect').dispatchEvent(new Event('change'))}window.scrollTo(0,0)}
function join(){hideViews();$('joinView').classList.remove('hidden');document.querySelector('.join-form').classList.remove('hidden');['joinName','joinPhone','joinEmail'].forEach(id=>$(id).value='');$('joinPickupAlerts').checked=true;$('joinStoreUpdates').checked=false;$('joinResult').innerHTML='';window.scrollTo(0,0)}
function addBack(view,fn,label='← Home'){if(!view||view.querySelector('.back-home'))return;const b=document.createElement('button');b.className='btn ghost back-home';b.textContent=label;b.onclick=fn;view.prepend(b)}
function signup(){ensure();const name=$('joinName').value.trim(),phone=$('joinPhone').value.trim(),email=$('joinEmail').value.trim().toLowerCase();if(!name)return alert('Please enter your name.');if(phoneKey(phone).length<7)return alert('Please enter a valid phone number.');if(!emailOK(email))return alert('Please enter a valid email address.');if(data.customers.some(c=>phoneKey(c.phone)===phoneKey(phone)))return alert('That phone number is already connected to a Roost Club member.');if(data.customers.some(c=>String(c.email||'').toLowerCase()===email))return alert('That email is already connected to a Roost Club member.');const c={id:uid('customer'),name,phone,email,pickupAlerts:$('joinPickupAlerts').checked,storeUpdates:$('joinStoreUpdates').checked,cartonCredits:0,totalCartons:0,freeDozens:0,createdAt:new Date().toISOString()};data.customers.push(c);persist();renderAll();document.querySelector('.join-form').classList.add('hidden');$('joinResult').innerHTML=`<div class="pickup-result welcome-roost"><h2>Welcome to the Roost, ${esc(c.name)}!</h2><div class="rsub">Carton Credits</div><div class="credit-number">0</div><p class="hint">Bring back clean, reusable dozen-egg cartons to earn credits toward a free dozen.</p><button class="btn primary wide" id="returnNow">Return Cartons Now</button><button class="btn ghost wide" id="signupDone">Done</button></div>`;$('returnNow').onclick=()=>cartons(c.id);$('signupDone').onclick=home}
function editMember(id){const c=data.customers.find(x=>x.id===id);if(!c)return;const name=prompt('Member name:',c.name);if(name===null||!name.trim())return;const phone=prompt('Phone:',c.phone||'');if(phone===null)return;if(phone&&phoneKey(phone).length<7)return alert('Enter a valid phone number.');const email=prompt('Email:',c.email||'');if(email===null)return;const e=email.trim().toLowerCase();if(e&&!emailOK(e))return alert('Enter a valid email address.');if(data.customers.some(x=>x.id!==id&&x.name.toLowerCase()===name.trim().toLowerCase()))return alert('Another member already has that name.');if(phone&&data.customers.some(x=>x.id!==id&&phoneKey(x.phone)===phoneKey(phone)))return alert('That phone number belongs to another member.');if(e&&data.customers.some(x=>x.id!==id&&String(x.email||'').toLowerCase()===e))return alert('That email belongs to another member.');c.name=name.trim();c.phone=phone.trim();c.email=e;c.updatedAt=new Date().toISOString();save()}
function adminPolish(){ensure();const tab=$('customersTab');if(!tab)return;[...tab.querySelectorAll('h2')].forEach(h=>{if(h.textContent==='Carton Club Settings')h.textContent='Roost Club Rewards';if(h.textContent==='Add Regular Customer')h.textContent='Add Roost Club Member';if(h.textContent==='Regular Customers')h.textContent='Roost Club Members'});const stat=$('cartonMembersAdmin')?.previousElementSibling;if(stat)stat.textContent='Roost Club Members';const form=$('cartonCustomerName')?.closest('.form');if(form&&!$('cartonCustomerEmail')){const f=document.createElement('div');f.className='field';f.innerHTML='<label>Email</label><input id="cartonCustomerEmail" type="email" placeholder="Email">';form.insertBefore(f,$('addCartonCustomer'));form.style.gridTemplateColumns='repeat(3,minmax(0,1fr)) auto'}const add=$('addCartonCustomer');if(add){add.textContent='Add Member';add.onclick=()=>{const name=$('cartonCustomerName').value.trim(),phone=$('cartonCustomerPhone').value.trim(),email=$('cartonCustomerEmail').value.trim().toLowerCase();if(!name)return alert('Enter the customer name.');if(phone&&phoneKey(phone).length<7)return alert('Enter a valid phone number.');if(email&&!emailOK(email))return alert('Enter a valid email address.');if(data.customers.some(c=>c.name.toLowerCase()===name.toLowerCase()))return alert('That customer is already saved.');if(phone&&data.customers.some(c=>phoneKey(c.phone)===phoneKey(phone)))return alert('That phone number is already saved.');if(email&&data.customers.some(c=>String(c.email||'').toLowerCase()===email))return alert('That email is already saved.');data.customers.push({id:uid('customer'),name,phone,email,pickupAlerts:false,storeUpdates:false,cartonCredits:0,totalCartons:0,freeDozens:0,createdAt:new Date().toISOString()});$('cartonCustomerName').value='';$('cartonCustomerPhone').value='';$('cartonCustomerEmail').value='';save()}}tab.querySelectorAll('[data-carton-edit]').forEach(btn=>{btn.onclick=()=>editMember(btn.dataset.cartonEdit);const c=data.customers.find(x=>x.id===btn.dataset.cartonEdit),sub=btn.closest('.row')?.querySelector('.rsub');if(c&&sub)sub.innerHTML=`${esc(c.phone||'No phone')}<div class="member-contact">${esc(c.email||'No email')}</div>`})}
const h=document.createElement('main');h.id='kioskHome';h.className='kiosk-home';h.innerHTML='<h1>Welcome to Rise & Roost</h1><p class="lead">What would you like to do?</p><div class="kiosk-grid"><button class="kiosk-choice" id="goShop">Shop<span>Browse items and check out</span></button><button class="kiosk-choice" id="goPickup">Pickup Order<span>Pick up an order waiting for you</span></button><button class="kiosk-choice" id="goRoost">The Roost<span>Carton rewards and member signup</span></button></div>';document.querySelector('.store-tabs').after(h);
const r=document.createElement('main');r.id='roostHub';r.className='roost-hub hidden';r.innerHTML='<button class="btn ghost back-home" id="roostBack">← Home</button><section class="card pickup-customer"><h2>The Roost</h2><p class="hint">Rewards for our regular customers.</p><div class="roost-actions"><button class="roost-action" id="goCartons">Return Egg Cartons<span>Add carton credits to your Roost profile.</span></button><button class="roost-action" id="goJoin">Join the Roost<span>Sign up with your name, phone, and email.</span></button></div></section>';h.after(r);
const j=document.createElement('main');j.id='joinView';j.className='join-wrap hidden';j.innerHTML='<button class="btn ghost back-home" id="joinBack">← The Roost</button><section class="card pickup-customer"><h2>Join the Roost</h2><p class="hint">Sign up once and keep your carton credits for future visits.</p><div class="join-form"><div class="field"><label>Name</label><input id="joinName" autocomplete="name" placeholder="Your name"></div><div class="field"><label>Phone number</label><input id="joinPhone" type="tel" autocomplete="tel" placeholder="Phone number"></div><div class="field"><label>Email</label><input id="joinEmail" type="email" autocomplete="email" placeholder="Email address"></div><label class="consent"><input id="joinPickupAlerts" type="checkbox" checked><span><strong>Pickup alerts</strong><br><span class="hint">Use my contact information for pickup-order notifications.</span></span></label><label class="consent"><input id="joinStoreUpdates" type="checkbox"><span><strong>Store updates & specials</strong><br><span class="hint">I want occasional Rise & Roost updates.</span></span></label><button class="btn primary wide pay" id="joinSubmit">Join the Roost</button></div><div id="joinResult"></div></section>';r.after(j);
addBack($('shopView'),home);addBack($('pickupView'),home);addBack($('cartonView'),roost,'← The Roost');$('goShop').onclick=shop;$('goPickup').onclick=pickup;$('goRoost').onclick=roost;$('roostBack').onclick=home;$('goCartons').onclick=()=>cartons();$('goJoin').onclick=join;$('joinBack').onclick=roost;$('joinSubmit').onclick=signup;
const oldRender=renderAll;renderAll=function(){ensure();oldRender();adminPolish()};const oldTab=showTab;showTab=function(name){oldTab(name);if(name==='customers')setTimeout(adminPolish,0)};document.querySelectorAll('.tab').forEach(t=>t.onclick=()=>showTab(t.dataset.tab));
const cartonH=$('cartonView')?.querySelector('h2');if(cartonH)cartonH.textContent='Roost Carton Rewards';const cartonP=$('cartonView')?.querySelector('p.hint');if(cartonP)cartonP.textContent='Choose your name, enter the number of clean reusable cartons, and collect your credits.';
$('exportBackup').onclick=()=>{const blob=new Blob([JSON.stringify({version:4,exportedAt:new Date().toISOString(),data},null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`rise-and-roost-v4-backup-${new Date().toISOString().slice(0,10)}.json`;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000)};
renderAll();home();
})();